alias compile='g++ -o'
alias evap='cd Desktop/TecDeMty/Sem4/evap'
alias debug='g++ -g'
alias l='ls -CF --color=auto'
alias l.='ls -d .* --color=auto'
alias la='ls -A --color=auto'
alias ll='ls -alF --color=auto'
alias ls='ls --color=auto'
