alias compile='g++ -o'
alias debug='g++ -g'
alias l='ls -CF --color=auto'
alias l.='ls -d .* --color=auto'
alias la='ls -A --color=auto'
alias ll='ls -alF --color=auto'
alias ls='ls --color=auto'
alias stailf='sudo tail -f'
alias fehbg='feh --bg-fill'
alias tailf='tail -f'
