alias compile='g++ -o'
alias compile11='g++ -o -std=c++11'
alias csoft='cd Desktop/TecDeMty/Sem3/Software'
alias debug='g++ -g'
alias debug11='g++ -g -std=c++11'
alias l='ls -CF --color=auto'
alias l.='ls -d .* --color=auto'
alias la='ls -A --color=auto'
alias ll='ls -alF --color=auto'
alias ls='ls --color=auto'
